### ISSUE TITLE
Advanced Queries link in readme 404s

### ISSUE THREAD

**Issue by Gigarayzor** [contentstack/datasync-content-store-mongodb#1]
This issue is actually for the contentstack/datasync-mongodb-sdk repo, not contentstack/datasync-content-store-mongodb. I'm submitting it here because that's where the link under 'Support and Feature requests' in the readme links. If it isn't supposed to link here, I can close this and submit two issues for the proper repo.

The issue I mean to report is the readme (for datasync-mongodb-sdk) has an 'Advanced Queries' section which links to API documentation, but that link results in a 404: https://contentstack.github.io/datasync-mongodb-sdk/

**Comment by ninadhatkar** [comment]
Thanks @Gigarayzor for bringing this to notice. We have resolved the 404 on the repositories.

**Comment by Gigarayzor** [comment]
Thanks!
